import { test, expect, type Browser, type Page } from '@playwright/test';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { randomBytes } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import NotificationService from '../../lib/notificationService';

/**
 * N1-01 — notification links built by the catalog, through the real bell.
 *
 * Notifications are generated by the live producer path
 * (`NotificationService.triggerNotification`, in-process with the service role;
 * immediate e-mail is switched off with NOTIFICATION_EMAIL_ENABLED=false).
 * A facilitator follows a session notification to the session record; an
 * outsider consultor from another school cannot open that record. A docente
 * attendee, notified as the session lifecycle producer does, follows the bell to the
 * session's meeting page (the consultor detail page would redirect them); a
 * docente from another school cannot open it. A listed attendee who is not in
 * the session's growth community, whom the meeting page answers 404, follows the
 * bell to the dashboard instead. A DB template whose link is a session URL with a
 * query (the N04-R3-01 counterexample) is stored as the dashboard when the payload
 * names no session, and the query variant of the meet URL is still 404 for that
 * attendee; for a member the query and trailing-slash variants reach the page and
 * a mis-cased or over-long path does not. A docente whose notifications lack a
 * usable record id lands on safe existing pages.
 *
 * Self-contained synthetic fixtures (*@qa.local.test, two qa schools) created in
 * beforeAll and deleted by id in afterAll. Refuses any non-local Supabase URL.
 */

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? '';
const DESKTOP = { width: 1366, height: 768 };
const MOBILE = { width: 390, height: 844 };
const EVIDENCE_DIR = process.env.UI_EVIDENCE_DIR;
const RUN = randomBytes(4).toString('hex');
const MARKER = `N04-${RUN}`;
const PASSWORD = `N04-${randomBytes(12).toString('base64url')}!a1`;
const SCHOOL_A = 9_400_000 + (parseInt(RUN.slice(0, 4), 16) % 100_000);
const SCHOOL_B = SCHOOL_A + 100_000;

type Persona = 'facilitator' | 'outsider' | 'learner' | 'attendee' | 'stranger' | 'nonmember';
const users: Record<Persona, { id: string; email: string; role: string; school: number }> = {
  facilitator: { id: '', email: `notif04-${RUN}-facilitator@qa.local.test`, role: 'consultor', school: SCHOOL_A },
  outsider: { id: '', email: `notif04-${RUN}-outsider@qa.local.test`, role: 'consultor', school: SCHOOL_B },
  learner: { id: '', email: `notif04-${RUN}-learner@qa.local.test`, role: 'docente', school: SCHOOL_A },
  attendee: { id: '', email: `notif04-${RUN}-attendee@qa.local.test`, role: 'docente', school: SCHOOL_A },
  stranger: { id: '', email: `notif04-${RUN}-stranger@qa.local.test`, role: 'docente', school: SCHOOL_B },
  /** Listed in session_attendees, same school, no growth-community role: the N04-R2-01 counterexample. */
  nonmember: { id: '', email: `notif04-${RUN}-nonmember@qa.local.test`, role: 'docente', school: SCHOOL_A },
};
const fixtures = { communityId: '', sessionId: '', triggerId: '' };
const evidence: Record<string, unknown> = { run: RUN, marker: MARKER, supabaseUrl: SUPABASE_URL, schools: [SCHOOL_A, SCHOOL_B] };
let service: SupabaseClient;

function assertLocal(url: string) {
  const host = new URL(url).hostname;
  if (!['127.0.0.1', 'localhost', '::1'].includes(host)) {
    throw new Error(`notification-catalog-links refuses non-local Supabase URL host ${host}`);
  }
}

async function shot(page: Page, name: string) {
  const dir = EVIDENCE_DIR ?? test.info().outputDir;
  mkdirSync(dir, { recursive: true });
  await page.screenshot({ path: join(dir, `${name}.png`), fullPage: false });
}

function must<T>(label: string, result: { data: T; error: { message: string } | null }): T {
  if (result.error) throw new Error(`${label}: ${result.error.message}`);
  return result.data;
}

async function createPersona(key: Persona, first: string) {
  const u = users[key];
  const created = await service.auth.admin.createUser({ email: u.email, password: PASSWORD, email_confirm: true });
  if (created.error) throw new Error(`createUser ${key}: ${created.error.message}`);
  u.id = created.data.user.id;
  must(`profile ${key}`, await service.from('profiles').upsert(
    { id: u.id, email: u.email, name: `${first} Sintetico`, first_name: first, last_name: 'Sintetico', must_change_password: false, approval_status: 'approved', school_id: u.school },
    { onConflict: 'id' }
  ));
  // The school-A docentes belong to the community, as a real message recipient and session attendee do.
  const communityId = key === 'learner' || key === 'attendee' ? fixtures.communityId : null;
  must(`role ${key}`, await service.from('user_roles').insert({ user_id: u.id, role_type: u.role, school_id: u.school, community_id: communityId, is_active: true }));
}

async function notificationsFor(userId: string) {
  return must('read notifications', await service
    .from('user_notifications')
    .select('id, title, related_url')
    .eq('user_id', userId)
    .order('created_at')) as Array<{ id: string; title: string; related_url: string }>;
}

async function signedIn(browser: Browser, key: Persona, viewport: typeof DESKTOP) {
  const context = await browser.newContext({ viewport, storageState: { cookies: [], origins: [] } });
  const page = await context.newPage();
  const foreign: string[] = [];
  page.on('request', (r) => {
    const { hostname } = new URL(r.url());
    if (!['127.0.0.1', 'localhost'].includes(hostname) && r.isNavigationRequest()) foreign.push(r.url());
  });
  await page.goto('/login');
  await page.getByPlaceholder('tu@email.com').fill(users[key].email);
  await page.locator('input[type="password"]').fill(PASSWORD);
  await page.getByRole('button', { name: /iniciar sesión/i }).click();
  await expect(page).toHaveURL(/\/dashboard(\?|$)/, { timeout: 60_000 });
  return { context, page, foreign };
}

async function openBell(page: Page, mobile: boolean) {
  if (mobile) await page.getByRole('button', { name: 'Abrir menú de navegación' }).click();
  const bell = page.getByRole('button', { name: /^Notificaciones/ });
  await expect(bell).toBeVisible({ timeout: 30_000 });
  await bell.click();
  await expect(page.getByRole('heading', { name: 'Notificaciones', level: 3 })).toBeVisible();
}

test.describe.configure({ mode: 'serial', timeout: 240_000 });

test.describe('notification catalog links (N1-01)', () => {
  test.beforeAll(async () => {
    test.setTimeout(120_000);
    if (!SUPABASE_URL || !SERVICE_KEY) throw new Error('Supabase URL and service key are required');
    if (process.env.NOTIFICATION_EMAIL_ENABLED !== 'false') throw new Error('NOTIFICATION_EMAIL_ENABLED=false is required');
    assertLocal(SUPABASE_URL);
    service = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });
    must('schools', await service.from('schools').insert([
      { id: SCHOOL_A, name: `Colegio Sintetico A ${MARKER}`, tenant_kind: 'qa' },
      { id: SCHOOL_B, name: `Colegio Sintetico B ${MARKER}`, tenant_kind: 'qa' },
    ]));
    const community = must('community', await service.from('growth_communities').insert({ name: `Comunidad ${MARKER}`, school_id: SCHOOL_A }).select('id').single()) as { id: string };
    fixtures.communityId = community.id;
    await createPersona('facilitator', 'Facilitadora');
    await createPersona('outsider', 'Externa');
    await createPersona('learner', 'Docente');
    await createPersona('attendee', 'Asistente');
    await createPersona('stranger', 'Ajena');
    await createPersona('nonmember', 'Listada');
    const session = must('session', await service.from('consultor_sessions').insert({
      school_id: SCHOOL_A, growth_community_id: community.id, title: `${MARKER} Taller`, session_date: '2030-01-15',
      start_time: '09:00', end_time: '10:30', modality: 'online', status: 'programada', created_by: users.facilitator.id,
    }).select('id').single()) as { id: string };
    fixtures.sessionId = session.id;
    must('facilitator', await service.from('session_facilitators').insert({ session_id: session.id, user_id: users.facilitator.id, facilitator_role: 'consultor_externo', is_lead: true }));
    must('attendees', await service.from('session_attendees').insert([
      { session_id: session.id, user_id: users.attendee.id },
      { session_id: session.id, user_id: users.nonmember.id },
    ]));

    const results = [
      await NotificationService.triggerNotification('session_created', {
        session: { id: session.id, title: `${MARKER} Taller`, date: '15-01-2030', time: '09:00' },
        facilitator_ids: [users.facilitator.id], attendee_ids: [],
      }),
      // Malformed record id: the link must fall back, never carry the value.
      await NotificationService.triggerNotification('assignment_feedback', {
        assignment_id: 'https://evil.example/x', student_id: users.learner.id, assignment_name: `${MARKER} Tarea`,
      }),
      await NotificationService.triggerNotification('message_sent', {
        message_id: `${MARKER}-m1`, recipient_id: users.learner.id, sender_name: 'Facilitadora Sintetico',
      }),
    ];
    for (const r of results) expect(r).toEqual({ success: true, notificationsCreated: 1 });
    // The lifecycle producer's payload (lib/services/session-lifecycle-notifications.ts): every
    // facilitator and attendee id goes in facilitator_ids. Its dynamic import of the service does
    // not resolve under the Playwright transpiler, so the spec sends the same payload directly.
    expect(await NotificationService.triggerNotification('session_rescheduled', {
      session: {
        id: session.id, title: `${MARKER} Taller`, date: '15-01-2030', time: '09:00', end_time: '10:30',
        previous_date: '14-01-2030', previous_time: '09:00', previous_end_time: '10:30', join_url: null,
      },
      facilitator_ids: [users.facilitator.id, users.attendee.id, users.nonmember.id],
      attendee_ids: [],
    })).toEqual({ success: true, notificationsCreated: 3 });
    // N04-R3-01: a live DB template (read through get_active_triggers) whose link is the meet URL
    // with a query, for an event whose payload names no session. The link must fall back.
    const trigger = must('trigger', await service.from('notification_triggers').insert({
      event_type: 'session_reminder_1h', category: 'sessions', is_active: true,
      notification_template: { title_template: `Recordatorio plantilla {session.title}`, description_template: 'Plantilla de prueba', url_template: `/meet/session/${session.id}?from=bell` },
    }).select('id').single()) as { id: string };
    fixtures.triggerId = trigger.id;
    expect(await NotificationService.triggerNotification('session_reminder_1h', {
      session: { id: 'sin-uuid', title: `${MARKER} Taller`, date: '15-01-2030', time: '09:00' },
      facilitator_ids: [users.attendee.id, users.nonmember.id], attendee_ids: [],
    })).toEqual({ success: true, notificationsCreated: 2 });
    evidence.fixtures = { users: Object.fromEntries(Object.entries(users).map(([k, v]) => [k, v.id])), ...fixtures };
  });

  test.afterAll(async () => {
    const ids = Object.values(users).map((u) => u.id).filter(Boolean);
    const cleanup: Record<string, number | string> = {};
    const count = (r: { error: { message: string } | null; count: number | null }) => (r.error ? r.error.message : r.count ?? -1);
    if (service) {
      cleanup.user_notifications = count(await service.from('user_notifications').delete({ count: 'exact' }).in('user_id', ids));
      const eventIds: string[] = [];
      for (const [path, value] of [['event_data->session->>title', `${MARKER} Taller`], ['event_data->>assignment_name', `${MARKER} Tarea`], ['event_data->>message_id', `${MARKER}-m1`]]) {
        const found = await service.from('notification_events').select('id').eq(path, value);
        eventIds.push(...(found.data ?? []).map((r: { id: string }) => r.id));
      }
      evidence.notificationEventIds = eventIds;
      cleanup.notification_events = count(await service.from('notification_events').delete({ count: 'exact' }).in('id', eventIds));
      if (fixtures.sessionId) {
        cleanup.session_attendees = count(await service.from('session_attendees').delete({ count: 'exact' }).eq('session_id', fixtures.sessionId));
        cleanup.session_facilitators = count(await service.from('session_facilitators').delete({ count: 'exact' }).eq('session_id', fixtures.sessionId));
        cleanup.consultor_sessions = count(await service.from('consultor_sessions').delete({ count: 'exact' }).eq('id', fixtures.sessionId));
      }
      if (fixtures.communityId) cleanup.growth_communities = count(await service.from('growth_communities').delete({ count: 'exact' }).eq('id', fixtures.communityId));
      if (fixtures.triggerId) cleanup.notification_triggers = count(await service.from('notification_triggers').delete({ count: 'exact' }).eq('id', fixtures.triggerId));
      cleanup.user_roles = count(await service.from('user_roles').delete({ count: 'exact' }).in('user_id', ids));
      cleanup.profiles = count(await service.from('profiles').delete({ count: 'exact' }).in('id', ids));
      let authDeleted = 0;
      for (const id of ids) if (!(await service.auth.admin.deleteUser(id)).error) authDeleted += 1;
      cleanup.auth_users = authDeleted;
      cleanup.schools = count(await service.from('schools').delete({ count: 'exact' }).in('id', [SCHOOL_A, SCHOOL_B]));
    }
    evidence.cleanup = cleanup;
    if (EVIDENCE_DIR) {
      mkdirSync(EVIDENCE_DIR, { recursive: true });
      writeFileSync(join(EVIDENCE_DIR, 'ui-evidence.json'), JSON.stringify(evidence, null, 2));
    }
  });

  test('UI1 desktop: facilitator follows the bell to the session; an outsider cannot open it', async ({ browser }) => {
    const [row] = await notificationsFor(users.facilitator.id);
    expect(row.related_url).toBe(`/consultor/sessions/${fixtures.sessionId}`);
    evidence.facilitatorUrl = row.related_url;

    const { context, page, foreign } = await signedIn(browser, 'facilitator', DESKTOP);
    await openBell(page, false);
    const item = page.getByText(`Sesión agendada: ${MARKER} Taller`);
    await expect(item).toBeVisible({ timeout: 30_000 });
    await shot(page, 'ui1-desktop-bell');
    await item.click();
    await expect(page).toHaveURL(new RegExp(`/consultor/sessions/${fixtures.sessionId}$`), { timeout: 30_000 });
    await expect(page.getByRole('heading', { name: `${MARKER} Taller`, level: 1 })).toBeVisible({ timeout: 30_000 });
    await shot(page, 'ui1-desktop-session-record');
    expect(foreign).toEqual([]);
    await context.close();

    const outsider = await signedIn(browser, 'outsider', DESKTOP);
    await openBell(outsider.page, false);
    await expect(outsider.page.getByText(`${MARKER} Taller`)).toHaveCount(0);
    await outsider.page.keyboard.press('Escape');
    await outsider.page.goto(row.related_url);
    await expect(outsider.page.getByRole('heading', { name: 'Sesión no encontrada' })).toBeVisible({ timeout: 30_000 });
    await expect(outsider.page.getByText(`${MARKER} Taller`)).toHaveCount(0);
    await shot(outsider.page, 'ui1-desktop-outsider-denied');
    await outsider.context.close();
  });

  test('R1 desktop and mobile: a docente attendee reaches the session; a docente from another school cannot', async ({ browser }) => {
    const rows = await notificationsFor(users.attendee.id);
    const title = `Sesión reprogramada: ${MARKER} Taller`;
    // The template reminder named no session, so even this member gets the dashboard, not the query URL.
    expect(rows.map((r) => [r.title, r.related_url])).toEqual([[title, `/meet/session/${fixtures.sessionId}`], [`Recordatorio plantilla ${MARKER} Taller`, '/dashboard']]);
    evidence.attendeeUrls = rows.map((r) => r.related_url);
    const facilitatorRows = await notificationsFor(users.facilitator.id);
    expect(facilitatorRows.find((r) => r.title === title)?.related_url).toBe(`/consultor/sessions/${fixtures.sessionId}`);

    for (const [viewport, mobile, name] of [[DESKTOP, false, 'desktop'], [MOBILE, true, 'mobile']] as const) {
      const { context, page, foreign } = await signedIn(browser, 'attendee', viewport);
      await openBell(page, mobile);
      await expect(page.getByText(title)).toBeVisible({ timeout: 30_000 });
      await shot(page, `r1-${name}-attendee-bell`);
      await page.getByText(title).click();
      await expect(page).toHaveURL(new RegExp(`/meet/session/${fixtures.sessionId}$`), { timeout: 30_000 });
      await expect(page.getByRole('heading', { name: `${MARKER} Taller`, level: 1 })).toBeVisible({ timeout: 30_000 });
      await expect(page.getByTestId('meet-back-link')).toBeVisible();
      await shot(page, `r1-${name}-attendee-session`);
      expect(foreign).toEqual([]);
      if (!mobile) {
        // The link r1 produced: the consultor detail page sends a docente away.
        await page.goto(`/consultor/sessions/${fixtures.sessionId}`);
        await expect(page).toHaveURL(/\/dashboard(\?|$)/, { timeout: 30_000 });
        // What Next.js routes for the session URL variants the classifier decides on (N04-R3-01):
        // query and trailing slash reach the page; a mis-cased route or an extra segment do not.
        const meet = `/meet/session/${fixtures.sessionId}`;
        const heading = page.getByRole('heading', { name: `${MARKER} Taller`, level: 1 });
        const probes: Record<string, unknown> = {};
        const query = await page.goto(`${meet}?from=bell`);
        await expect(page).toHaveURL(new RegExp(`${meet}\\?from=bell$`));
        await expect(heading).toBeVisible({ timeout: 30_000 });
        probes.query = { status: query?.status(), url: new URL(page.url()).pathname + new URL(page.url()).search };
        await shot(page, 'r1-desktop-attendee-query-variant');
        const slash = await page.goto(`${meet}/`);
        await expect(page).toHaveURL(new RegExp(`${meet}$`));
        await expect(heading).toBeVisible({ timeout: 30_000 });
        probes.trailingSlash = { status: slash?.status(), redirected: !!slash?.request().redirectedFrom(), url: new URL(page.url()).pathname };
        const upper = await page.goto(`/MEET/SESSION/${fixtures.sessionId}`);
        probes.upperCase = upper?.status();
        expect(upper?.status()).toBe(404);
        const extra = await page.goto(`${meet}/resumen`);
        probes.extraSegment = extra?.status();
        expect(extra?.status()).toBe(404);
        await expect(page.getByText(`${MARKER} Taller`)).toHaveCount(0);
        evidence.routeProbes = probes;
        expect(probes).toMatchObject({ query: { status: 200 }, trailingSlash: { status: 200, redirected: true, url: meet } });
      }
      await context.close();
    }

    const stranger = await signedIn(browser, 'stranger', DESKTOP);
    await openBell(stranger.page, false);
    await expect(stranger.page.getByText(`${MARKER} Taller`)).toHaveCount(0);
    await stranger.page.keyboard.press('Escape');
    const response = await stranger.page.goto(rows[0].related_url);
    expect(response?.status()).toBe(404);
    await expect(stranger.page.getByText('This page could not be found')).toBeVisible({ timeout: 30_000 });
    await expect(stranger.page.getByText(`${MARKER} Taller`)).toHaveCount(0);
    await shot(stranger.page, 'r1-desktop-stranger-denied');
    await stranger.context.close();
  });

  test('D7 desktop and mobile: a listed attendee outside the community lands on the dashboard, not the meet page 404', async ({ browser }) => {
    const rows = await notificationsFor(users.nonmember.id);
    const rescheduled = `Sesión reprogramada: ${MARKER} Taller`;
    const templated = `Recordatorio plantilla ${MARKER} Taller`;
    expect(rows.map((r) => [r.title, r.related_url])).toEqual([[rescheduled, '/dashboard'], [templated, '/dashboard']]);
    evidence.nonmemberUrls = rows.map((r) => r.related_url);

    // Desktop follows the DB-template variant (N04-R3-01), mobile the catalog link (N04-R2-01).
    for (const [viewport, mobile, name, title] of [[DESKTOP, false, 'desktop', templated], [MOBILE, true, 'mobile', rescheduled]] as const) {
      const { context, page, foreign } = await signedIn(browser, 'nonmember', viewport);
      // Leave the dashboard first, through the sidebar as a user would, so the bell item is seen to navigate back.
      if (mobile) await page.getByRole('button', { name: 'Abrir menú de navegación' }).click();
      await page.getByRole('button', { name: 'Mi Perfil Información personal' }).click();
      await expect(page).toHaveURL(/\/profile(\?|$)/, { timeout: 30_000 });
      await openBell(page, mobile);
      await expect(page.getByText(title)).toBeVisible({ timeout: 30_000 });
      await shot(page, `d7-${name}-nonmember-bell`);
      await page.getByText(title).click();
      await expect(page).toHaveURL(/\/dashboard(\?|$)/, { timeout: 30_000 });
      await expect(page.getByRole('heading', { name: '¡Hola, Listada!', level: 1 })).toBeVisible({ timeout: 30_000 });
      await expect(page.getByText('This page could not be found')).toHaveCount(0);
      await shot(page, `d7-${name}-nonmember-dashboard`);
      expect(foreign).toEqual([]);
      if (!mobile) {
        // The link r2 produced for this attendee: the meeting page answers 404 with no session title.
        const response = await page.goto(`/meet/session/${fixtures.sessionId}`);
        expect(response?.status()).toBe(404);
        await expect(page.getByText('This page could not be found')).toBeVisible({ timeout: 30_000 });
        await expect(page.getByText(`${MARKER} Taller`)).toHaveCount(0);
        await shot(page, 'd7-desktop-nonmember-meet-denied');
        // The template's query variant of the same URL: still not found, still no title.
        const query = await page.goto(`/meet/session/${fixtures.sessionId}?from=bell`);
        expect(query?.status()).toBe(404);
        await expect(page.getByText('This page could not be found')).toBeVisible({ timeout: 30_000 });
        await expect(page.getByText(`${MARKER} Taller`)).toHaveCount(0);
        await shot(page, 'd7-desktop-nonmember-meet-query-denied');
      }
      await context.close();
    }
  });

  test('UI2 mobile: links without a usable record go to safe existing pages', async ({ browser }) => {
    const rows = await notificationsFor(users.learner.id);
    expect(rows.map((r) => r.related_url)).toEqual(['/assignments', '/community/workspace?section=messaging']);
    evidence.learnerUrls = rows.map((r) => r.related_url);

    const { context, page, foreign } = await signedIn(browser, 'learner', MOBILE);
    await openBell(page, true);
    await expect(page.getByText(rows[0].title)).toBeVisible({ timeout: 30_000 });
    await shot(page, 'ui2-mobile-bell');
    await page.getByText(rows[0].title).click();
    await expect(page).toHaveURL(/\/assignments$/, { timeout: 30_000 });
    // The empty state of the learner's task list: a usable page, not a dead link.
    await expect(page.getByText('No se encontraron tareas.')).toBeVisible({ timeout: 30_000 });
    await expect(page.getByPlaceholder('Buscar tareas...')).toBeVisible();
    await shot(page, 'ui2-mobile-assignments-fallback');

    await openBell(page, true);
    await page.getByRole('heading', { name: rows[1].title, level: 4 }).click();
    await expect(page).toHaveURL(/\/community\/workspace\?section=messaging$/, { timeout: 30_000 });
    await expect(page.getByRole('button', { name: 'Abrir menú de navegación' })).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText('This page could not be found')).toHaveCount(0);
    await shot(page, 'ui2-mobile-messaging-fallback');
    expect(foreign).toEqual([]);
    await context.close();
  });
});
