/**
 * QA Confirm Expected Outcomes Page
 *
 * Interface for reviewing and editing "NEEDS CONFIRMATION" expected outcomes
 * in scenarios generated by Claude Code.
 */

import { useSupabaseClient } from '@supabase/auth-helpers-react';
import React, { useEffect, useState, useCallback } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { toast } from 'react-hot-toast';
import MainLayout from '@/components/layout/MainLayout';
import {
  ArrowLeft,
  AlertTriangle,
  CheckCircle2,
  Save,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';
import type { QAScenario, QAScenarioStep, FeatureArea } from '@/types/qa';
import { FEATURE_AREA_LABELS } from '@/types/qa';

interface UnconfirmedStep {
  scenarioId: string;
  scenarioName: string;
  featureArea: FeatureArea;
  stepIndex: number;
  instruction: string;
  expectedOutcome: string;
  originalOutcome: string;
}

const QAConfirmOutcomesPage: React.FC = () => {
  const router = useRouter();
  const supabase = useSupabaseClient();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [hasPermission, setHasPermission] = useState<boolean | null>(null);
  const [avatarUrl, setAvatarUrl] = useState<string>('');

  const [unconfirmedSteps, setUnconfirmedSteps] = useState<UnconfirmedStep[]>([]);
  const [editedOutcomes, setEditedOutcomes] = useState<Record<string, string>>({});
  const [expandedScenario, setExpandedScenario] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  // Check auth and permissions
  useEffect(() => {
    const checkAuth = async () => {
      const {
        data: { session },
      } = await supabase.auth.getSession();
      if (!session?.user) {
        router.push('/login');
        return;
      }
      setUser(session.user);

      // Get avatar
      const { data: profileData } = await supabase
        .from('profiles')
        .select('avatar_url')
        .eq('id', session.user.id)
        .single();

      if (profileData?.avatar_url) {
        setAvatarUrl(profileData.avatar_url);
      }

      // Check permissions (admin only)
      const { data: roles } = await supabase
        .from('user_roles')
        .select('role_type')
        .eq('user_id', session.user.id)
        .eq('is_active', true);

      const isAdmin = roles?.some((r) => r.role_type === 'admin') || false;
      setHasPermission(isAdmin);
    };

    checkAuth();
  }, [supabase, router]);

  // Fetch scenarios with unconfirmed steps
  const fetchUnconfirmedSteps = useCallback(async () => {
    if (!user || hasPermission === false) return;

    setLoading(true);
    try {
      const response = await fetch('/api/qa/scenarios');
      if (!response.ok) {
        throw new Error('Error al cargar escenarios');
      }

      const data = await response.json();
      const scenarios: QAScenario[] = data.scenarios || [];

      // Find steps with "???" or "NEEDS CONFIRMATION"
      const unconfirmed: UnconfirmedStep[] = [];
      scenarios.forEach((scenario) => {
        scenario.steps.forEach((step) => {
          if (
            step.expectedOutcome.includes('???') ||
            step.expectedOutcome.includes('NEEDS CONFIRMATION')
          ) {
            const key = `${scenario.id}-${step.index}`;
            unconfirmed.push({
              scenarioId: scenario.id,
              scenarioName: scenario.name,
              featureArea: scenario.feature_area,
              stepIndex: step.index,
              instruction: step.instruction,
              expectedOutcome: step.expectedOutcome,
              originalOutcome: step.expectedOutcome,
            });
          }
        });
      });

      setUnconfirmedSteps(unconfirmed);

      // Initialize edited outcomes
      const initial: Record<string, string> = {};
      unconfirmed.forEach((step) => {
        const key = `${step.scenarioId}-${step.stepIndex}`;
        initial[key] = step.expectedOutcome;
      });
      setEditedOutcomes(initial);
    } catch (error: any) {
      console.error('Error fetching scenarios:', error);
      toast.error(error.message || 'Error al cargar escenarios');
    } finally {
      setLoading(false);
    }
  }, [user, hasPermission]);

  useEffect(() => {
    if (user && hasPermission === true) {
      fetchUnconfirmedSteps();
    }
  }, [user, hasPermission, fetchUnconfirmedSteps]);

  // Group steps by scenario
  const groupedByScenario = unconfirmedSteps.reduce((acc, step) => {
    if (!acc[step.scenarioId]) {
      acc[step.scenarioId] = {
        scenarioName: step.scenarioName,
        featureArea: step.featureArea,
        steps: [],
      };
    }
    acc[step.scenarioId].steps.push(step);
    return acc;
  }, {} as Record<string, { scenarioName: string; featureArea: FeatureArea; steps: UnconfirmedStep[] }>);

  // Save a single step's expected outcome
  const handleSaveStep = async (scenarioId: string, stepIndex: number) => {
    const key = `${scenarioId}-${stepIndex}`;
    const newOutcome = editedOutcomes[key];

    if (!newOutcome || newOutcome.includes('???') || newOutcome.includes('NEEDS CONFIRMATION')) {
      toast.error('Por favor, proporciona un resultado esperado válido');
      return;
    }

    setSaving(true);
    try {
      // Fetch the current scenario
      const response = await fetch(`/api/qa/scenarios/${scenarioId}`);
      if (!response.ok) {
        throw new Error('Error al cargar escenario');
      }

      const scenario: QAScenario = await response.json();

      // Update the step
      const updatedSteps = scenario.steps.map((step) => {
        if (step.index === stepIndex) {
          return { ...step, expectedOutcome: newOutcome };
        }
        return step;
      });

      // Save the scenario
      const saveResponse = await fetch(`/api/qa/scenarios/${scenarioId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ steps: updatedSteps }),
      });

      if (!saveResponse.ok) {
        const data = await saveResponse.json();
        throw new Error(data.error || 'Error al guardar');
      }

      // Remove from unconfirmed list
      setUnconfirmedSteps((prev) =>
        prev.filter((s) => !(s.scenarioId === scenarioId && s.stepIndex === stepIndex))
      );

      toast.success('Resultado esperado actualizado');
    } catch (error: any) {
      console.error('Error saving step:', error);
      toast.error(error.message || 'Error al guardar');
    } finally {
      setSaving(false);
    }
  };

  // Save all edited steps for a scenario
  const handleSaveScenario = async (scenarioId: string) => {
    const scenarioSteps = unconfirmedSteps.filter((s) => s.scenarioId === scenarioId);

    // Validate all have proper outcomes
    for (const step of scenarioSteps) {
      const key = `${step.scenarioId}-${step.stepIndex}`;
      const outcome = editedOutcomes[key];
      if (!outcome || outcome.includes('???') || outcome.includes('NEEDS CONFIRMATION')) {
        toast.error(`Paso ${step.stepIndex}: Por favor, proporciona un resultado esperado válido`);
        return;
      }
    }

    setSaving(true);
    try {
      // Fetch the current scenario
      const response = await fetch(`/api/qa/scenarios/${scenarioId}`);
      if (!response.ok) {
        throw new Error('Error al cargar escenario');
      }

      const scenario: QAScenario = await response.json();

      // Update all steps
      const updatedSteps = scenario.steps.map((step) => {
        const key = `${scenarioId}-${step.index}`;
        if (editedOutcomes[key] !== undefined) {
          return { ...step, expectedOutcome: editedOutcomes[key] };
        }
        return step;
      });

      // Save the scenario
      const saveResponse = await fetch(`/api/qa/scenarios/${scenarioId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ steps: updatedSteps }),
      });

      if (!saveResponse.ok) {
        const data = await saveResponse.json();
        throw new Error(data.error || 'Error al guardar');
      }

      // Remove all steps from this scenario from unconfirmed list
      setUnconfirmedSteps((prev) => prev.filter((s) => s.scenarioId !== scenarioId));

      toast.success(`${scenarioSteps.length} paso(s) actualizado(s)`);
    } catch (error: any) {
      console.error('Error saving scenario:', error);
      toast.error(error.message || 'Error al guardar');
    } finally {
      setSaving(false);
    }
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
    localStorage.removeItem('rememberMe');
    sessionStorage.removeItem('sessionOnly');
    router.push('/login');
  };

  // Loading state
  if (loading && hasPermission === null) {
    return (
      <div className="min-h-screen bg-brand_beige flex justify-center items-center">
        <p className="text-xl text-brand_primary">Cargando...</p>
      </div>
    );
  }

  // Access denied
  if (hasPermission === false) {
    return (
      <MainLayout
        user={user}
        currentPage="qa-admin"
        pageTitle=""
        breadcrumbs={[]}
        isAdmin={false}
        onLogout={handleLogout}
        avatarUrl={avatarUrl}
      >
        <div className="flex flex-col justify-center items-center min-h-[50vh]">
          <div className="text-center p-8">
            <h1 className="text-2xl font-semibold text-brand_primary mb-4">
              Acceso Denegado
            </h1>
          </div>
        </div>
      </MainLayout>
    );
  }

  return (
    <MainLayout
      user={user}
      currentPage="qa-admin"
      pageTitle=""
      breadcrumbs={[]}
      isAdmin={true}
      onLogout={handleLogout}
      avatarUrl={avatarUrl}
    >
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        {/* Header */}
        <div className="flex items-center gap-4 mb-6">
          <Link
            href="/admin/qa"
            className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <ArrowLeft className="w-5 h-5 text-gray-600" />
          </Link>
          <div>
            <h1 className="text-xl font-bold text-gray-900">
              Confirmar Resultados Esperados
            </h1>
            <p className="text-sm text-gray-500">
              Revisa y edita los resultados esperados pendientes de confirmación
            </p>
          </div>
        </div>

        {/* Info Box */}
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-yellow-500 flex-shrink-0 mt-0.5" />
            <div>
              <h2 className="font-semibold text-yellow-800">
                ¿Qué son los resultados pendientes de confirmar?
              </h2>
              <p className="text-sm text-yellow-700 mt-1">
                Cuando Claude Code genera escenarios, algunos resultados esperados pueden marcarse con
                &quot;??? (NEEDS CONFIRMATION)&quot; si no está seguro del comportamiento exacto.
                Revisa estos pasos y proporciona el resultado esperado correcto.
              </p>
            </div>
          </div>
        </div>

        {/* Content */}
        {loading ? (
          <div className="text-center py-12">
            <p className="text-gray-500">Cargando escenarios...</p>
          </div>
        ) : unconfirmedSteps.length === 0 ? (
          <div className="text-center bg-white p-12 rounded-xl shadow-lg">
            <CheckCircle2 className="mx-auto h-16 w-16 text-green-500/50" />
            <h3 className="mt-4 text-xl font-semibold text-gray-900">
              ¡Todo confirmado!
            </h3>
            <p className="mt-2 text-sm text-gray-600">
              No hay resultados esperados pendientes de confirmar.
            </p>
            <Link
              href="/admin/qa/scenarios"
              className="inline-block mt-6 px-4 py-2 bg-brand_primary text-white rounded-lg text-sm font-medium hover:bg-brand_gray_dark transition-colors"
            >
              Ver Escenarios
            </Link>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="bg-white rounded-lg shadow-md p-4 mb-4">
              <p className="text-sm text-gray-700">
                <span className="font-semibold">{unconfirmedSteps.length}</span> paso(s) en{' '}
                <span className="font-semibold">{Object.keys(groupedByScenario).length}</span> escenario(s)
                pendiente(s) de confirmar
              </p>
            </div>

            {Object.entries(groupedByScenario).map(([scenarioId, { scenarioName, featureArea, steps }]) => (
              <div key={scenarioId} className="bg-white rounded-lg shadow-md overflow-hidden">
                <button
                  onClick={() =>
                    setExpandedScenario(expandedScenario === scenarioId ? null : scenarioId)
                  }
                  className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-gray-50 transition-colors"
                >
                  <div>
                    <h3 className="font-medium text-gray-900">{scenarioName}</h3>
                    <p className="text-sm text-gray-500">
                      {FEATURE_AREA_LABELS[featureArea]} • {steps.length} paso(s) pendiente(s)
                    </p>
                  </div>
                  {expandedScenario === scenarioId ? (
                    <ChevronUp className="w-5 h-5 text-gray-400" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-400" />
                  )}
                </button>

                {expandedScenario === scenarioId && (
                  <div className="px-6 pb-6 border-t border-gray-100">
                    <div className="space-y-6 mt-4">
                      {steps.map((step) => {
                        const key = `${step.scenarioId}-${step.stepIndex}`;
                        return (
                          <div
                            key={key}
                            className="border border-gray-200 rounded-lg p-4"
                          >
                            <div className="flex items-start justify-between mb-3">
                              <div>
                                <span className="text-xs font-medium text-gray-500 uppercase">
                                  Paso {step.stepIndex}
                                </span>
                                <p className="text-sm text-gray-900 mt-1">
                                  {step.instruction}
                                </p>
                              </div>
                            </div>

                            <div className="mb-3">
                              <label className="block text-xs font-medium text-yellow-700 mb-1">
                                Resultado esperado actual (pendiente de confirmar):
                              </label>
                              <p className="text-sm text-yellow-600 bg-yellow-50 p-2 rounded">
                                {step.originalOutcome}
                              </p>
                            </div>

                            <div>
                              <label
                                htmlFor={key}
                                className="block text-xs font-medium text-gray-700 mb-1"
                              >
                                Nuevo resultado esperado:
                              </label>
                              <textarea
                                id={key}
                                value={editedOutcomes[key] || ''}
                                onChange={(e) =>
                                  setEditedOutcomes((prev) => ({
                                    ...prev,
                                    [key]: e.target.value,
                                  }))
                                }
                                placeholder="Describe el resultado esperado correcto..."
                                rows={2}
                                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-1 focus:ring-brand_accent"
                              />
                            </div>

                            <div className="mt-3 flex justify-end">
                              <button
                                onClick={() => handleSaveStep(step.scenarioId, step.stepIndex)}
                                disabled={saving}
                                className="px-3 py-1.5 text-sm bg-brand_primary text-white rounded-lg hover:bg-brand_gray_dark transition-colors disabled:opacity-50 flex items-center gap-1"
                              >
                                <Save className="w-3 h-3" />
                                Guardar Paso
                              </button>
                            </div>
                          </div>
                        );
                      })}
                    </div>

                    {steps.length > 1 && (
                      <div className="mt-6 pt-4 border-t border-gray-200 flex justify-end">
                        <button
                          onClick={() => handleSaveScenario(scenarioId)}
                          disabled={saving}
                          className="px-4 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors disabled:opacity-50 flex items-center gap-2"
                        >
                          <CheckCircle2 className="w-4 h-4" />
                          Guardar Todo el Escenario
                        </button>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </MainLayout>
  );
};

export default QAConfirmOutcomesPage;
