/**
 * Cache-or-generate serving for the two Pasantías PDFs (D-05).
 *
 * Both routes — `/api/pasantias/brochure` and `/api/pasantias/ficha` — do the
 * same four things in the same order, and they have to keep doing them the same
 * way: the download contract is public, and a divergence between the two would
 * be a bug nobody sees until a reader gets the wrong header. Hence one handler
 * factory parameterised by document, cache version, filename and generator.
 *
 * MANUAL OVERRIDE (D-05, and the reason the cache is read before anything else)
 * — whatever object sits at the cache path is served AS-IS. The generator only
 * runs on a miss. That is not an accident of caching: it is the supported way
 * the owner publishes a hand-designed brochure (Decision Log 2026-08-02), which
 * is uploaded to the cache path after per-file approval and then served
 * verbatim, unversioned by anything this code does.
 *
 * WHO MAY WRITE THE CACHE — reads are unconditional in every environment, but
 * only production uploads generated bytes. The `propuestas` bucket lives on the
 * one Supabase instance every environment shares, and outside production the
 * origin the generators print comes from local or preview configuration (a
 * developer's `.env.local` says `http://localhost:3000`). An unconditional
 * upload therefore lets any cold-cache request from anywhere publish a document
 * with the wrong CTA at the path production serves. Reading cannot poison
 * anything, and a warm production object is exactly what a preview should show,
 * so the gate is on the write alone.
 *
 * The two rules interact: an owner-uploaded designed brochure is a manual write
 * to the same path, so it is served everywhere, unchanged by this gate — only
 * *generated* bytes are production-gated.
 *
 * D-01: this module must never import `cohort-commercial.ts`. The commercial
 * filename and version arrive as plain parameters, so the ficha route's import
 * graph stays free of prices — proved by the allowlist test in
 * `lib/pasantias/__tests__/pdf.test.ts`.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { handleMethodNotAllowed } from '../../api-auth';
import { RATE_LIMITS, withRateLimit } from '../../rateLimit';
import { downloadFile, uploadFile } from '../../propuestas/storage';
import { buildContentDisposition } from './filenames';

/** Prefix of both cache keys inside the `propuestas` bucket. */
export const PASANTIAS_CACHE_PREFIX = 'pasantias';

/** `Cache-Control` max-age for both documents, in seconds. */
export const PDF_MAX_AGE_SECONDS = 3600;

/** The two documents A4 serves; also the `<name>` half of the cache key. */
export type PasantiasDocument = 'brochure' | 'ficha';

export interface PasantiasPdfRoute {
  document: PasantiasDocument;
  /** Cache version — `BROCHURE_VERSION` or `FICHA_VERSION`. */
  version: string;
  /** Download filename; must satisfy `isRfc5987SafeFilename`. */
  filename: string;
  /** A3's generator, called only on a cache miss. */
  generate: () => Promise<Buffer>;
}

/** D-05's cache key: `pasantias/<name>-<VERSION>.pdf` in the `propuestas` bucket. */
export function pasantiasCachePath(document: PasantiasDocument, version: string): string {
  return `${PASANTIAS_CACHE_PREFIX}/${document}-${version}.pdf`;
}

function describe(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

/**
 * Whether this runtime may write generated bytes to the shared cache.
 *
 * `VERCEL_ENV` is the only signal that separates production from preview — both
 * run a production build, so `NODE_ENV` cannot tell them apart — and it is unset
 * off-platform, which is precisely the local case this gate exists to stop.
 * Anything other than the literal `production` therefore serves without
 * uploading.
 */
function mayWriteCache(): boolean {
  return process.env.VERCEL_ENV === 'production';
}

/**
 * Build the API handler for one document.
 *
 * The rate limit is best-effort dampening only (D-04): the durable cost control
 * is the cache above it, since a hit costs one bucket read and no rendering.
 */
export function createPasantiasPdfHandler(route: PasantiasPdfRoute) {
  const path = pasantiasCachePath(route.document, route.version);

  async function handler(req: NextApiRequest, res: NextApiResponse): Promise<void> {
    if (req.method !== 'GET') {
      handleMethodNotAllowed(res, ['GET']);
      return;
    }

    let pdf: Buffer | null = null;

    try {
      pdf = await downloadFile(path);
    } catch (err) {
      // A miss and an unreachable bucket look the same from here, and the
      // response is the same either way: generate it now.
      console.log(`[pasantias-pdf] cache miss for ${path}: ${describe(err)}`);
    }

    if (!pdf) {
      try {
        // Deliberately generated WITHOUT the request: the bytes are cached in a
        // bucket every deployment shares, so the URL they print must not depend
        // on which deployment happened to miss the cache first. `app-url.ts`
        // resolves the configured origin (D-09) and never the Host header in
        // production.
        pdf = await route.generate();
      } catch (err) {
        console.error(`[pasantias-pdf] could not generate ${route.document}: ${describe(err)}`);
        res.status(500).json({
          error: 'No se pudo generar el documento. Intente nuevamente en unos minutos.',
        });
        return;
      }

      if (mayWriteCache()) {
        try {
          await uploadFile(path, pdf, 'application/pdf');
        } catch (err) {
          // A broken bucket must not break the download: we already hold the
          // bytes, so the request still succeeds and only the caching is lost.
          console.error(`[pasantias-pdf] could not cache ${path}: ${describe(err)}`);
        }
      } else {
        // Said out loud so nobody spends an afternoon wondering why the cache
        // never warms up locally.
        console.info(
          `[pasantias-pdf] not caching ${path}: generated bytes are uploaded only when ` +
            `VERCEL_ENV=production (here it is ${process.env.VERCEL_ENV ?? 'unset'}), because the ` +
            'propuestas bucket is shared with production. Serving the freshly generated document.'
        );
      }
    }

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', buildContentDisposition(route.filename));
    res.setHeader('Cache-Control', `public, max-age=${PDF_MAX_AGE_SECONDS}`);
    res.setHeader('Content-Length', pdf.length);
    res.status(200).end(pdf);
  }

  return withRateLimit(handler, RATE_LIMITS.readonly, `pasantias-${route.document}`);
}
