import type { PropuestaFichaServicioInsert } from '@/lib/propuestas/types';

/**
 * Seed data for propuesta_fichas_servicio
 * All 9 registered ATE services from the MINEDUC Certificado de Pertenencia.
 * Source: Certificado de Pertenencia — Fundación Instituto Relacional
 */
export const FICHAS_SEED: PropuestaFichaServicioInsert[] = [
  {
    folio: 45450,
    nombre_servicio: 'Fortalecimiento del Clima Relacional para Mejorar la Gestión Educativa',
    dimension: 'Liderazgo',
    categoria: 'Asesoría',
    horas_presenciales: 48,
    horas_no_presenciales: 0,
    total_horas: 48,
    destinatarios: [
      'Docentes',
      'Directores',
      'Sostenedores',
      'Profesionales de Apoyo a la labor educativa',
      'Asistentes de la Educación',
    ],
    objetivo_general: null,
    metodologia: null,
    equipo_trabajo: null,
    fecha_inscripcion: '2018-07-20',
    activo: true,
  },
  {
    folio: 45451,
    nombre_servicio: 'Liderazgo para el cambio de la cultura organizacional',
    dimension: 'Liderazgo',
    categoria: 'Asesoría',
    horas_presenciales: 20,
    horas_no_presenciales: 0,
    total_horas: 20,
    destinatarios: [
      'Docentes',
      'Directores',
      'Sostenedores',
      'Profesionales de Apoyo a la labor educativa',
      'Asistentes de la Educación',
    ],
    objetivo_general: null,
    metodologia: null,
    equipo_trabajo: null,
    fecha_inscripcion: '2018-07-24',
    activo: true,
  },
  {
    folio: 45615,
    nombre_servicio: 'Capacitación Fortalecimiento de equipos para plasmar el PEI y viabilizar el PME.',
    dimension: 'Liderazgo',
    categoria: 'Capacitación',
    horas_presenciales: 20,
    horas_no_presenciales: 0,
    total_horas: 20,
    destinatarios: [
      'Docentes',
      'Directores',
      'Sostenedores',
      'Profesionales de Apoyo a la labor educativa',
      'Asistentes de la Educación',
    ],
    objetivo_general: null,
    metodologia: null,
    equipo_trabajo: null,
    fecha_inscripcion: '2018-07-24',
    activo: true,
  },
  {
    folio: 46064,
    nombre_servicio: 'Capacitación para liderar una cultura de innovación educativa en la escuela',
    dimension: 'Liderazgo',
    categoria: 'Capacitación',
    horas_presenciales: 88,
    horas_no_presenciales: 0,
    total_horas: 88,
    destinatarios: [
      'Docentes',
      'Directores',
      'Sostenedores',
      'Profesionales de Apoyo a la labor educativa',
      'Asistentes de la Educación',
    ],
    objetivo_general: null,
    metodologia: null,
    equipo_trabajo: null,
    fecha_inscripcion: '2018-09-12',
    activo: true,
  },
  {
    folio: 46729,
    nombre_servicio: 'Herramientas Psicoemocionales para Promover en los Estudiantes la Motivación hacia el Aprendizaje',
    dimension: 'Gestión Pedagógica',
    categoria: 'Capacitación',
    horas_presenciales: 20,
    horas_no_presenciales: 0,
    total_horas: 20,
    destinatarios: [
      'Docentes',
      'Directores',
      'Sostenedores',
      'Profesionales de Apoyo a la labor educativa',
      'Asistentes de la Educación',
    ],
    objetivo_general: null,
    metodologia: null,
    equipo_trabajo: null,
    fecha_inscripcion: '2018-12-13',
    activo: true,
  },
  {
    folio: 47849,
    nombre_servicio: 'Implementación de Aprendizaje Basado en Proyectos (ABP)',
    dimension: 'Gestión Pedagógica',
    categoria: 'Capacitación',
    horas_presenciales: 80,
    horas_no_presenciales: 0,
    total_horas: 80,
    destinatarios: [
      'Docentes',
      'Directores',
      'Sostenedores',
      'Profesionales de Apoyo a la labor educativa',
      'Asistentes de la Educación',
    ],
    objetivo_general: null,
    metodologia: null,
    equipo_trabajo: null,
    fecha_inscripcion: '2019-02-11',
    activo: true,
  },
  {
    folio: 47940,
    nombre_servicio: 'Adquisición de estrategias para disponer corporal y emocionalmente al aprendizaje',
    dimension: 'Gestión Pedagógica',
    categoria: 'Capacitación',
    horas_presenciales: 25,
    horas_no_presenciales: 0,
    total_horas: 25,
    destinatarios: [
      'Docentes',
      'Directores',
      'Sostenedores',
      'Profesionales de Apoyo a la labor educativa',
      'Asistentes de la Educación',
    ],
    objetivo_general: null,
    metodologia: null,
    equipo_trabajo: null,
    fecha_inscripcion: '2019-02-11',
    activo: true,
  },
  {
    folio: 48083,
    nombre_servicio: 'Introducción a la metodología ABP para Líderes y Docentes',
    dimension: 'Gestión Pedagógica',
    categoria: 'Capacitación',
    horas_presenciales: 32,
    horas_no_presenciales: 0,
    total_horas: 32,
    destinatarios: [
      'Docentes',
      'Directores',
      'Sostenedores',
      'Profesionales de Apoyo a la labor educativa',
      'Asistentes de la Educación',
    ],
    objetivo_general: null,
    metodologia: null,
    equipo_trabajo: null,
    fecha_inscripcion: '2019-02-11',
    activo: true,
  },
  {
    folio: 52244,
    nombre_servicio: 'Asesoría Integral para Desarrollar una Cultura de Innovación Educativa Centrada en el Aprendizaje',
    dimension: 'Liderazgo',
    categoria: 'Capacitación',
    horas_presenciales: 148,
    horas_no_presenciales: 0,
    total_horas: 148,
    destinatarios: [
      'Sostenedores',
      'Asistentes de la Educación',
      'Docentes',
      'Profesionales de Apoyo a la labor educativa',
      'Directores',
    ],
    objetivo_general:
      'Facilitar el diseño e implementación de un proceso participativo de innovación y cambio, que cree las bases de una cultura centrada en el aprendizaje, a partir de metodologías activas y colaborativas para el desarrollo de las competencias del S. XXI',
    metodologia: 'Reflexión grupal / grupo de discusión, Clases demostrativas, Intercambio de experiencias.',
    equipo_trabajo: [
      { nombre: 'Gabriela Naranjo Armas', formacion: 'Psicóloga', anos_experiencia: 3 },
      { nombre: 'Jeannette LaFors', formacion: 'Estudios Americanos (Historiadora)', anos_experiencia: 3 },
      { nombre: 'Ignacio Pavez', formacion: 'Título de Ingeniero Civil', anos_experiencia: 4 },
      { nombre: 'Cesar Andrés Lillo Morales', formacion: 'Asistente Social', anos_experiencia: 1 },
      { nombre: 'Arnoldo Cisternas Chávez', formacion: 'Psicólogo', anos_experiencia: 3 },
      { nombre: 'Marcela Bloomfield García', formacion: 'Profesora de Educación Musical', anos_experiencia: 1 },
    ],
    fecha_inscripcion: '2020-03-20',
    activo: true,
  },
];
